{% set name = "de421" %}
{% set version = "2008.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a66faf7be328573d0028e45632ba614dd573cee88e3b6f099059149acc024df8

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - de421

about:
  home: https://github.com/brandon-rhodes/python-jplephem/ 
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'This is a recent short-period ephemeris published by the Jet Propulsion Laboratory. It requires only 27 MB of storage and is specially accurate with respect to the position of Earth’s Moon.'

  description: |
    The JPL called this ephemeris is a “significant advance” over predecessors like DE405 / DE406 and cited accuracies that are in many cases ten times greater, such as giving the position of Venus within 200m and the positions of Earth and Mars within 300m over the last decade. Note that even greater accuracies are achieved, for Mercury and Venus in particular (but not for the Moon), by DE423 which also has the advantage of covering a 400-year period instead of only 150 years.
  doc_url: https://github.com/brandon-rhodes/python-jplephem/
  dev_url: https://github.com/brandon-rhodes/python-jplephem/

extra:
  recipe-maintainers:
    - ReimarBauer

