{% set name = "Flask-Migrate" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 57d6060839e3a7f150eaab6fe4e726d9e3e7cffe2150fb223d73f92421c6d1d9

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python
  host:
    - python
    - pip
  run:
    - python
    - Flask >= 0.9
    - Flask-SQLAlchemy >= 1.0
    - alembic >= 0.7

test:
  imports:
    - flask_migrate
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/miguelgrinberg/Flask-Migrate
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'SQLAlchemy database migrations for Flask applications using Alembic.'
  description: |
    Flask-Migrate is an extension that handles SQLAlchemy database migrations for
    Flask applications using Alembic. The database operations are provided as
    command-line arguments under the flask db command.
  doc_url: https://flask-migrate.readthedocs.io/en/latest/
  dev_url: https://github.com/miguelgrinberg/flask-migrate

extra:
  recipe-maintainers:
    - ReimarBauer
