{% set name = "fs_filepicker" %}
{% set version = "0.0.2" %}
{% set sha256 = "b556fe3b75ed7e93e5bf2c83f6ea7863e8f73fbd85cf115eabb0f1f1f0dcb743" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/ReimarBauer/fs_filepicker/archive/0.0.2.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - future

  run:
    - python
    - pyqt 5.*
    - fs
    - future

test:
  imports:
    - fslib.fs_filepicker

about:
  home: https://github.com/ReimarBauer/fs_filepicker
  license: APACHE 2.0
  license_file: LICENSE
  summary: 'QT file picker for accessing a pyfilesystem2'
  dev_url: https://github.com/ReimarBauer/fs_filepicker

extra:
  recipe-maintainers:
    - ReimarBauer
